In [ ]:
from math import inf
#psuedo code of the node
''' class Node:
Attributes
 . feature: the feature index used for splitting
 . threshold: the value to split the feature on.

'''

class Node:
  def __init__(self, feature=None, threshold=None, left=None, right=None, *, value=None):
    self.feature = feature
    self.threshold = threshold
    self.left = left
    self.right = right
    self.value = value

  def is_leaf_node(self):
    return self.value is not None
class DecisionTreeRegressor:
  def __init__(self):
    self.root=None
  def fit(self,X,y):
   self.root=self._build_tree(X,y)
  def _build_tree(self,X,y, depth=0):
    n_samples, n_features = X.shape
    n_labels = len(np.unique(y))
    if(n_labels==1):
      leaf_value=self._mean_of_labels(y)
      return Node(value=leaf_value)
    feat_idx=np.arange(n_features)
    best_feature, best_threshold = self._best_split(X, y,feat_idx)
    left_idxs, right_idxs = self._split(X[:, best_feature], best_threshold)
    left=self._build_tree(X[left_idxs,:],y[left_idxs])
    right=self._build_tree(X[right_idxs,:],y[right_idxs])
    return Node(best_feature,best_threshold,left,right)
  def _most_common_label(self,y):
    unique_labels,counts=np.unique(y,return_counts=True)
    return unique_labels[np.argmax(counts)] # argmax return index of the max value
  def _mean_of_labels(self,y):
    return np.mean(y)
  def _split(self,X_column,split_thresh):
    left_idxs=np.argwhere(X_column<=split_thresh).flatten()
    right_idxs=np.argwhere(X_column>split_thresh).flatten()
    return left_idxs,right_idxs
  def _best_split(self,X,y,feat_idxs):
    best_gain,split_idx,split_thresh=float('inf'),None,None
    for feat_idx in feat_idxs:
      X_column=X[:,feat_idx]
      X_column_sorted=np.sort(X_column)
      thresholds=(X_column_sorted[:-1]+X_column_sorted[1:])/2
      for threshold in thresholds:
        gain=self._information_gain(y,X_column,threshold)
        if(gain<best_gain):
          best_gain=gain
          split_idx=feat_idx
          split_thresh=threshold
      return split_idx,split_thresh
  def _information_gain(self,y,X_column,threshold):
    left_idxs, right_idxs=self._split(X_column,threshold)
    if(len(left_idxs)==0 or len(right_idxs)==0):
      return 0
    n,n_l,n_r = len(y),len(left_idxs),len(right_idxs)
    e_l,e_r=self._entropy(y[left_idxs]),self._entropy(y[right_idxs])
    child_entropy=(n_l/n)*e_l+(n_r/n)*e_r
    information_gain= child_entropy
    return information_gain
  def _entropy(self,y):#calculating mean square error or deviation
    y1=y-np.mean(y)
    return np.mean((y1-y)**2)
  def predict(self,X):
    pred= np.array([self._traverse_tree(x,self.root) for x in X])
    return pred
  def _traverse_tree(self,x,node):
    if node.is_leaf_node():
      return node.value
    if x[node.feature]<=node.threshold:
      return self._traverse_tree(x,node.left)
    return self._traverse_tree(x,node.right)



In [ ]:
import numpy as np
X=np.array([[1,2],[2,3],[3,4],[4,5],[5,6]])
y=np.array([1,1,0,0,0])
regressor=DecisionTreeRegressor()
regressor.fit(X,y)
y_pred=regressor.predict(X)
print(y_pred)

[1. 1. 0. 0. 0.]


In [ ]:
#evaluate the model
mse=np.mean((y-y_pred)**2)
print(f"mean square error : {mse:.2f}")

mean square error : 0.00


In [ ]:
def r2_score_percentage(y_true,y_pred):
  #calcualte the total sum of squares(TSS)
  tss=np.sum((y_true-np.mean(y_true))**2)
  #calcualte the residual sum of squares(rss)
  rss=np.sum((y_true-y_pred)**2)
  r2_score=1-(rss/tss)
  r2_precentage=r2_score*100
  return r2_precentage

In [ ]:
r2_score=r2_score_percentage(y,y_pred)

In [ ]:
r2_score

100.0

In [ ]:
from math import inf
#psuedo code of the node
''' class Node:
Attributes
 . feature: the feature index used for splitting
 . threshold: the value to split the feature on.

'''

class Node:
  def __init__(self, feature=None, threshold=None, left=None, right=None, *, value=None):
    self.feature = feature
    self.threshold = threshold
    self.left = left
    self.right = right
    self.value = value

  def is_leaf_node(self):
    return self.value is not None
class DecisionTreeRegressor:
  def __init__(self,max_depth):
    self.root=None
    self.max_depth=max_depth
  def fit(self,X,y):
   self.root=self._build_tree(X,y)
  def _build_tree(self,X,y, depth=0):
    n_samples, n_features = X.shape
    n_labels = len(np.unique(y))
    if(n_labels==1 or self.max_depth is not None and depth>=self.max_depth):
      leaf_value=self._mean_of_labels(y)
      return Node(value=leaf_value)
    feat_idx=np.arange(n_features)
    best_feature, best_threshold = self._best_split(X, y,feat_idx)
    left_idxs, right_idxs = self._split(X[:, best_feature], best_threshold)
    left=self._build_tree(X[left_idxs,:],y[left_idxs],depth+1)
    right=self._build_tree(X[right_idxs,:],y[right_idxs],depth+1)
    return Node(best_feature,best_threshold,left,right)
  def _most_common_label(self,y):
    unique_labels,counts=np.unique(y,return_counts=True)
    return unique_labels[np.argmax(counts)] # argmax return index of the max value
  def _mean_of_labels(self,y):
    return np.mean(y)
  def _split(self,X_column,split_thresh):
    left_idxs=np.argwhere(X_column<=split_thresh).flatten()
    right_idxs=np.argwhere(X_column>split_thresh).flatten()
    return left_idxs,right_idxs
  def _best_split(self,X,y,feat_idxs):
    best_gain,split_idx,split_thresh=float('inf'),None,None
    for feat_idx in feat_idxs:
      X_column=X[:,feat_idx]
      X_column_sorted=np.sort(X_column)
      thresholds=(X_column_sorted[:-1]+X_column_sorted[1:])/2
      for threshold in thresholds:
        gain=self._information_gain(y,X_column,threshold)
        if(gain<best_gain):
          best_gain=gain
          split_idx=feat_idx
          split_thresh=threshold
      return split_idx,split_thresh
  def _information_gain(self,y,X_column,threshold):
    left_idxs, right_idxs=self._split(X_column,threshold)
    if(len(left_idxs)==0 or len(right_idxs)==0):
      return 0
    n,n_l,n_r = len(y),len(left_idxs),len(right_idxs)
    e_l,e_r=self._entropy(y[left_idxs]),self._entropy(y[right_idxs])
    child_entropy=(n_l/n)*e_l+(n_r/n)*e_r
    information_gain= child_entropy
    return information_gain
  def _entropy(self,y):#calculating mean square error or deviation
    y1=y-np.mean(y)
    return np.mean((y1-y)**2)
  def predict(self,X):
    pred= np.array([self._traverse_tree(x,self.root) for x in X])
    return pred
  def _traverse_tree(self,x,node):
    if node.is_leaf_node():
      return node.value
    if x[node.feature]<=node.threshold:
      return self._traverse_tree(x,node.left)
    return self._traverse_tree(x,node.right)



In [ ]:
regressor=DecisionTreeRegressor(max_depth=3)

In [ ]:
regressor.fit(X,y)

In [ ]:
y_pred=regressor.predict(X)

In [ ]:
y_pred

array([1. , 0.5, 0.5, 0. , 0. ])

#using sklearn gradient boosting

In [ ]:
from sklearn.ensemble import GradientBoostingRegressor
X=np.array([[1,2],[2,3],[3,4],[4,5],[5,6]])
y=np.array([1,1,0,0,0])
regressor=GradientBoostingRegressor(n_estimators=100,learning_rate=0.1,max_depth=2,random_state=42)
regressor.fit(X,y)
y_pred=regressor.predict(X)
y_pred

array([9.99984063e-01, 9.99984063e-01, 1.06245596e-05, 1.06245596e-05,
       1.06245596e-05])

In [ ]:
mse=np.mean((y-y_pred)**2)
print(f"mean square error : {mse:.2f}")

mean square error : 0.00


In [ ]:
r2_score=r2_score_percentage(y,y_pred)

In [ ]:
r2_score

99.99999992944922

#without inbuilt functions

In [ ]:
from math import inf
class Node:
  def __init__(self, n_estimators=100,learning_rate=0.01,max_depth=1):
    self.n_estimators=n_estimators
    self.learning_rate=learning_rate
    self.max_depth=max_depth
    self.trees=[]

  def is_leaf_node(self):
    return self.value is not None
class DecisionTree:
  def __init__(self):
    self.root=None
  def fit(self,X,y):
    m=len(y)
    self.intial_prediction=np.mean(y)
    residuals=y-self.intial_prediction
    for _ in range(self.n_estimators):
      tree=DecisionTreeRegressor(max_depth=self.max_depth)
      tree.fit(X,residuals)
      predictions=tree.predict(X)
      residuals-=self.learning_rate*predictions
      self.trees.append(tree)
  def _most_common_label(self,y):
    unique_labels,counts=np.unique(y,return_counts=True)
    return unique_labels[np.argmax(counts)]
  def _build_tree(self,X,y, depth=0):
    n_samples, n_features = X.shape
    n_labels = len(np.unique(y))
    if(n_labels==1):
      leaf_value=self._most_common_label(y)
      return Node(value=leaf_value)
    feat_idx=np.arange(n_features)
    best_feature, best_threshold = self._best_split(X, y,feat_idx)
    left_idxs, right_idxs = self._split(X[:, best_feature], best_threshold)
    left=self._build_tree(X[left_idxs,:],y[left_idxs])
    right=self._build_tree(X[right_idxs,:],y[right_idxs])
    return Node(best_feature,best_threshold,left,right)
   # argmax return index of the max value
  def _split(self,X_column,split_thresh):
    left_idxs=np.argwhere(X_column<=split_thresh).flatten()
    right_idxs=np.argwhere(X_column>split_thresh).flatten()
    return left_idxs,right_idxs
  def _best_split(self,X,y,feat_idxs):
    best_gain,split_idx,split_thresh=float('inf'),None,None
    for feat_idx in feat_idxs:
      X_column=X[:,feat_idx]
      X_column_sorted=np.sort(X_column)
      thresholds=(X_column_sorted[:-1]+X_column_sorted[1:])/2
      for threshold in thresholds:
        gain=self._information_gain(y,X_column,threshold)
        if(gain<best_gain):
          best_gain=gain
          split_idx=feat_idx
          split_thresh=threshold
      return split_idx,split_thresh
  def _information_gain(self,y,X_column,threshold):
    left_idxs, right_idxs=self._split(X_column,threshold)
    if(len(left_idxs)==0 or len(right_idxs)==0):
      return 0
    n,n_l,n_r = len(y),len(left_idxs),len(right_idxs)
    e_l,e_r=self._entropy(y[left_idxs]),self._entropy(y[right_idxs])
    child_entropy=(n_l/n)*e_l+(n_r/n)*e_r
    information_gain= child_entropy
    return information_gain
  def _entropy(self,y):
    fid3=np.mean(y)
    if fid3==0 or fid3==1:
      return 0
    return -fid3*np.log(fid3)- (1-fid3)*np.log(1-fid3)
  def predict(self,X):
    y_pred=np.full(X.shape[0],self.intial_prediction)
    for tree in self.trees:
      y_pred+=self.learning_rate*tree.predict(X)
    return y_pred
  def _traverse_tree(self,x,node):
    if node.is_leaf_node():
      return node.value
    if x[node.feature]<=node.threshold:
      return self._traverse_tree(x,node.left)
    return self._traverse_tree(x,node.right)

class RandomForest:
  def __init__(self,n_trees=10,n_features=None):
    self.n_trees=n_trees
    self.n_features=n_features
    self.trees=[]
  def _most_common_label(self,y):
    unique_labels,counts=np.unique(y,return_counts=True)
    return unique_labels[np.argmax(counts)]
  def fit(self,X,y):
    self.trees=[]
    for _ in range(self.n_trees):
      tree=DecisionTree()
      X_sample,y_sample=self._bootstrap_sample(X,y)
      tree.fit(X_sample,y_sample)
      self.trees.append(tree)
  def _bootstrap_sample(self,X,y):
    n_samples,n_features=X.shape
    idxs=np.random.choice(n_samples,n_samples,replace=True)
    return X[idxs],y[idxs]
  def predict(self,X):
    preds=np.array([tree.predict(X) for tree in self.trees])
    tree_preds=np.swapaxes(preds,0,1)
    preds=np.array([self._most_common_label(tree_pred) for tree_pred in tree_preds])
    return pred

In [ ]:
re=GradientBoostingRegressor(n_estimators=100,learning_rate=0.1,max_depth=10)
re.fit(X,y)
y_pred=re.predict(X)
mse=np.mean((y-y_pred)**2)
print(f"mean square error : {mse:.2f}")

mean square error : 0.00


In [ ]:
r2_score=r2_score_percentage(y,y_pred)
print(r2_score)

#ADA boosting using sklern

In [ ]:
from sklearn.ensemble import AdaBoostClassifier

In [ ]:
X=np.array([[1,2],[2,3],[3,4],[4,5],[5,6]])
y=np.array([1,1,0,0,0])
clf=AdaBoostClassifier(n_estimators=50,learning_rate=0.1,random_state=42,algorithm='SAMME')
clf.fit(X,y)
y_pred=clf.predict(X)


In [ ]:
def acc(y_test,y_pred):
  return np.mean(y_test==y_pred)
accuracy=acc(y,y_pred)

In [ ]:
accuracy

1.0

#without inbuilt functions

In [ ]:
class AdaBoostWithTreeStump:
  def __init__(self,n_estimators=50):
    self.n_estimators=n_estimators
    self.alphas=[]
    self.models=[]
  def fit(X,y):
    m=X.shape[0]
    weights=np.ones(m)/m
    for _ in range(self.n_estimators):
      stump=DecisionTree(max_depth=1)
      stump.fit(X,y)
      predictions=stump.predict(X)
      error=np.sum(predictions !=y)/m
      if error==0:
        alpha=1e10
      else:
        alpha=0.5*np.log((1-error)/error)
      self.alphas.append(alpha)
      self.models.append(stump)
      new_weights=[]
      for i in range(m):
        if predictions[i]==y[i]:
          new_weight=weights[i]*np.exp(-alpha)
        else:
          new_weight=weights[i]*np.exp(-alpha)
        new_weights.append(new_weight)
      min_weight=1e-10
      new_weights=[max(W,min_weight) for W in new_weights]
      weight_sum=np.sum(new_weights)
      weights=[W/weight_sum for W in new_weights]
      #weights/=np.sum(weights)
      cumulative_weights=np.cumsum(weights)
      random_values=np.random.rand(m)
      indices=np.searchsorted(cumulative_weights,random_values)
      X,y=X[indices],y[indices]
    def predict(self,X):
      m=len(x)
      final_pred=np.zeros(m)
      for alpha, model in zip(self.alphas, self.models):
        predictions=model.predict(X)
        final_pred+=alpha*predictions
      return np.where(final_pred>0,1,0)
