#PCA


In [ ]:
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

X=np.array([[126,78],[128,80],[128,82],[130,82],[130,84],[132,86]])
pca=PCA()
X_projected=pca.fit_transform(X)
print(X_projected)
#print(pca.explained_variance_ratio_)

[[-4.99953747 -0.06800833]
 [-2.20523715  0.37003933]
 [-0.58906316 -0.80808699]
 [ 0.58906316  0.80808699]
 [ 2.20523715 -0.37003933]
 [ 4.99953747  0.06800833]]


In [ ]:
'''using numpy'''
class PCA1:
  def __init__(self):
    self.components=None #if self.components=1
    self.mean=None
  def fit(self,X):
    self.mean=np.mean(X,axis=0)
    X=X-self.mean
    cov=np.cov(X.T,ddof=1)
    eigenvalues,eigenvectors=np.linalg.eig(cov)
    idx=eigenvalues.argsort()[::-1]
    eigenvalues=eigenvalues[idx]
    eigenvectors=eigenvectors[:,idx]
    print(eigenvectors)
    X_projected=np.dot(X,eigenvectors.T)
    return X_projected# return X_projected[]



In [ ]:
pca2=PCA1()
X_projected1=pca2.fit(X)
print(X_projected1)
print("shape of x: ",X.shape)
print("shape of x_projected: ",X_projected1.shape)

[[-0.58906316 -0.80808699]
 [-0.80808699  0.58906316]]
[[ 4.99953747  0.06800833]
 [ 2.20523715 -0.37003933]
 [ 0.58906316  0.80808699]
 [-0.58906316 -0.80808699]
 [-2.20523715  0.37003933]
 [-4.99953747 -0.06800833]]
shape of x:  (6, 2)
shape of x_projected:  (6, 2)


In [ ]:
'''using numpy using components'''
class PCA3:
  def __init__(self):
    self.components=1
    self.mean=None
  def fit(self,X):
    self.mean=np.mean(X,axis=0)
    X=X-self.mean
    cov=np.cov(X.T,ddof=1)
    eigenvalues,eigenvectors=np.linalg.eig(cov)
    idx=eigenvalues.argsort()[::-1]
    eigenvalues=eigenvalues[idx]
    eigenvectors=eigenvectors[:,idx]
    #print(eigenvectors)
    X_projected=np.dot(X,eigenvectors.T)
    #X_projected=X_projected[:,:self.components]
    #print(X_projected)
    new_array=[]
    for x in X_projected:
      new_array.append(x[:self.components])
    X_projected=np.array(new_array)
    #print(new_array'''
    return X_projected# return X_projected[]



In [ ]:
pca3=PCA3()
X_projected12=pca3.fit(X)
print(X_projected12)
print("shape of x: ",X.shape)
print("shape of x_projected: ",X_projected12.shape)

[[ 4.99953747]
 [ 2.20523715]
 [ 0.58906316]
 [-0.58906316]
 [-2.20523715]
 [-4.99953747]]
shape of x:  (6, 2)
shape of x_projected:  (6, 1)
